/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    //field variable
    public int x;
    //constructor
    public App(){
        this.x = 0;
    }
    public App(int randomName){
        this.x = randomName;
    }
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        if(args.length <= 2){
            throw new RuntimeException();
        }
        // will kick off assuming args is greater than zero.
        bitMap(args[0], args[1], args[2]);
    }

    private static int bitMap(String inputFile, String outputFile, String method){
        String inputFileName = inputFile;
        String outputFileName = outputFile;
        String methodName = method;
        if (methodName.equals("method1")){
            // invoke bmp transformer

        } else if (methodName.equals( "method2")) {

        }else {

        }


        return 0;
    }
}
